# Generated by Django 3.2.25 on 2025-03-10 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('player', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='created_date',
        ),
        migrations.AddField(
            model_name='player',
            name='age',
            field=models.CharField(max_length=110, null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='club',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='team',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='player',
            name='name',
            field=models.TextField(blank=True, null=True),
        ),
    ]
