# Generated by Django 3.2.25 on 2025-03-10 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('player', '0002_auto_20250310_1225'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='title',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
