# Generated by Django 3.2.25 on 2025-03-24 10:52

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('player', '0003_player_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='created_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
