# Generated by Django 3.2.25 on 2025-03-24 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('player', '0005_auto_20250324_1213'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='title',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
