# Generated by Django 3.2.25 on 2025-03-24 11:31

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('player', '0006_player_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='title',
            field=models.CharField(default=django.utils.timezone.now, max_length=200),
            preserve_default=False,
        ),
    ]
