# Generated by Django 3.2.25 on 2025-03-24 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('player', '0007_alter_player_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='title',
            field=models.TextField(blank=True, max_length=200, null=True),
        ),
    ]
