# Generated by Django 3.2.25 on 2025-03-10 11:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_player'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Player',
        ),
    ]
